//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/New Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""JustinController"",
            ""id"": ""8e7a0f27-9199-4a35-b75a-1c6a5a85777e"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""a9f069e6-03f7-4b51-95b8-e82d9b7964f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkipDialog"",
                    ""type"": ""Button"",
                    ""id"": ""0e8a2aa8-a21d-41fd-9854-1eb1a7291f19"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TimeTravel"",
                    ""type"": ""Button"",
                    ""id"": ""abcaadaf-5708-4149-90d5-cc58a4244800"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""0e5c7bf1-bb90-4935-80c2-6539545b0eca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""891b8b16-c518-422c-b464-d1a042bfaaba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InputSpeed"",
                    ""type"": ""Value"",
                    ""id"": ""cccb962b-6502-4afc-adc1-984915e32c5e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Grab"",
                    ""type"": ""Button"",
                    ""id"": ""0e30fa49-5a6d-4eb1-a700-34ab6be2a9aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""386ce9d2-b77a-47dd-bfb4-902acef7d57b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""819f004f-683d-4eb9-9ca9-e2b7651974d8"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91104dbd-5f3f-4d78-a491-fa3f830e8ca3"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TimeTravel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""555a7781-de84-4e13-a42d-961e5ed3f7eb"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba13e3cf-1980-42d8-bea3-66a0bd149410"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d57d858-6d3d-47f5-a585-922b2844b75b"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InputSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fb60d46-5be2-48d0-b66d-dfbb32099218"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // JustinController
        m_JustinController = asset.FindActionMap("JustinController", throwIfNotFound: true);
        m_JustinController_Jump = m_JustinController.FindAction("Jump", throwIfNotFound: true);
        m_JustinController_SkipDialog = m_JustinController.FindAction("SkipDialog", throwIfNotFound: true);
        m_JustinController_TimeTravel = m_JustinController.FindAction("TimeTravel", throwIfNotFound: true);
        m_JustinController_Shoot = m_JustinController.FindAction("Shoot", throwIfNotFound: true);
        m_JustinController_Dash = m_JustinController.FindAction("Dash", throwIfNotFound: true);
        m_JustinController_InputSpeed = m_JustinController.FindAction("InputSpeed", throwIfNotFound: true);
        m_JustinController_Grab = m_JustinController.FindAction("Grab", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // JustinController
    private readonly InputActionMap m_JustinController;
    private IJustinControllerActions m_JustinControllerActionsCallbackInterface;
    private readonly InputAction m_JustinController_Jump;
    private readonly InputAction m_JustinController_SkipDialog;
    private readonly InputAction m_JustinController_TimeTravel;
    private readonly InputAction m_JustinController_Shoot;
    private readonly InputAction m_JustinController_Dash;
    private readonly InputAction m_JustinController_InputSpeed;
    private readonly InputAction m_JustinController_Grab;
    public struct JustinControllerActions
    {
        private @NewControls m_Wrapper;
        public JustinControllerActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_JustinController_Jump;
        public InputAction @SkipDialog => m_Wrapper.m_JustinController_SkipDialog;
        public InputAction @TimeTravel => m_Wrapper.m_JustinController_TimeTravel;
        public InputAction @Shoot => m_Wrapper.m_JustinController_Shoot;
        public InputAction @Dash => m_Wrapper.m_JustinController_Dash;
        public InputAction @InputSpeed => m_Wrapper.m_JustinController_InputSpeed;
        public InputAction @Grab => m_Wrapper.m_JustinController_Grab;
        public InputActionMap Get() { return m_Wrapper.m_JustinController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(JustinControllerActions set) { return set.Get(); }
        public void SetCallbacks(IJustinControllerActions instance)
        {
            if (m_Wrapper.m_JustinControllerActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnJump;
                @SkipDialog.started -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnSkipDialog;
                @SkipDialog.performed -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnSkipDialog;
                @SkipDialog.canceled -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnSkipDialog;
                @TimeTravel.started -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnTimeTravel;
                @TimeTravel.performed -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnTimeTravel;
                @TimeTravel.canceled -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnTimeTravel;
                @Shoot.started -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnShoot;
                @Dash.started -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnDash;
                @InputSpeed.started -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnInputSpeed;
                @InputSpeed.performed -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnInputSpeed;
                @InputSpeed.canceled -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnInputSpeed;
                @Grab.started -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnGrab;
                @Grab.performed -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnGrab;
                @Grab.canceled -= m_Wrapper.m_JustinControllerActionsCallbackInterface.OnGrab;
            }
            m_Wrapper.m_JustinControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @SkipDialog.started += instance.OnSkipDialog;
                @SkipDialog.performed += instance.OnSkipDialog;
                @SkipDialog.canceled += instance.OnSkipDialog;
                @TimeTravel.started += instance.OnTimeTravel;
                @TimeTravel.performed += instance.OnTimeTravel;
                @TimeTravel.canceled += instance.OnTimeTravel;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @InputSpeed.started += instance.OnInputSpeed;
                @InputSpeed.performed += instance.OnInputSpeed;
                @InputSpeed.canceled += instance.OnInputSpeed;
                @Grab.started += instance.OnGrab;
                @Grab.performed += instance.OnGrab;
                @Grab.canceled += instance.OnGrab;
            }
        }
    }
    public JustinControllerActions @JustinController => new JustinControllerActions(this);
    public interface IJustinControllerActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnSkipDialog(InputAction.CallbackContext context);
        void OnTimeTravel(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnInputSpeed(InputAction.CallbackContext context);
        void OnGrab(InputAction.CallbackContext context);
    }
}
